markupdeclaration/markupdeclaration.org

_pages/03_history.md

This page isn't linked from anywhere yet; maybe it doesn't need to be, but I didn't want the details to be lost entirely.

Moved some of the history stuff onto its own page

---

_pages/02_contact.md

Added link to markup declaration mailing list.

Updated contacts page

---

index.md

I believe we need to look forward. XML is used a lot and we should not for some reason be too negative.

replacing "revitalizing" by "explaining"

---

_pages/02_contact.md
index.md

I don't think this one needs editorial approval.

Fix mulberrytech links: http=>https

---

index.md

we need to add more examples of industries. 
I also added something I spoke about at Balisage: that the time was ripe now.

added more industries + time is ripe now

---

.gitignore

Just added .gradle/ directory and marked the other two entries as directories with the trailing "/".

Tweaked .gitignore

---

index.md

I started by having a problem with "requiring the reuse, long term preservation", then it snowballed.
En-dashes trump hyphens.

"requiring the reuse, long term preservation" doesn't scan

---

_pages/04_resources.md
css/mdecl.css

(Har har, pun intended)
1. The link to the bibliography was wrong
2. The CSS was making the logo distorted on narrow (phone-size) pages

Fix markup issues

---

_pages/DeclarativeMarkupDocs.html

Added entry for 'Extremes of XML' - XML London 2013.

Biblio extremes of xml

---

_pages/04_01_bibliography.html

I added the ones @btusdin suggested as well as Balisage and MarkupUK.

Added other collections of Markup-related materials

---

_pages/04_01_bibliography.html

Fixed a typo ("This list list..." in intro). Resolves #23

Typo fix in 04_01_bibliography.html

---

src/index.md

Jean asked me a while back to make sure we had links to the issues on the home page.

Add links to our issues lists to the home page

---

src/resources/events.md

Added DHSI, ACH, DocEng

---

src/resources/events.md

* Curated lists
* Computers & Writing
* The many hats of...

Added another couple, added pointers to other curated lists

---

src/resources/events.html

Per https://lists.mulberrytech.com/archive/markupdeclaration/msg/65-markup-events-calendar

Added Mitchell Hour

---

build.gradle
css/mdecl.css
includes/footer/default.xml
includes/head/default.xml
includes/header/default.xml
includes/header/main.xml
js/mdecl.js
src/contact.md
src/index.md
src/resources/bibliography.html
tools/xpl/docbook.xpl
tools/xpl/html.xpl
tools/xpl/markdown.xpl
tools/xsl/post.xsl

This PR redesigns the site to make links easier to access and to tighten up the front page text. (There will be another round of editorial proposals later.)
You can preview the new design at https://mdecltest.nwalsh.com/

First attempt at an improved design

---

src/about.md
src/contact.md
src/index.md

I don't think there's anything controversial in here.

A few small editorial improvements

---

src/resources/event-history.html
src/resources/events.html

Removed events that have already occurred.

Removed past events

---

src/resources/index.md

The lists haven't had much love since they were created.

Links to 'technologies' and 'applications' GitHub projects.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/resources/event-history.html
src/resources/events.html

I moved the June events to the archive page and added a workshop in November.

Events page updates

---

src/resources/events.html

Added workshop to events page.

Added Textual Editing in the Digital Age workshop
